
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Common": "common",
  "Ext": "ext/src",
  "Ext.Msg": "ext/src/window/MessageBox.js",
  "Ext.rtl.EventObjectImpl": "ext/src/rtl/EventObject.js",
  "Ext.ux.layout.component.field.BoxSelectField": "ext/src/ux/form/field/BoxSelect.js",
  "Overrides": "overrides",
  "Wenjoy": "app"
});
Ext.ClassManager.addNameAlternateMappings({
  "Common.permission.Permission": [
    "permission"
  ],
  "Common.util.Config": [
    "config"
  ],
  "Common.util.Util": [
    "util"
  ],
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.Action": [],
  "Ext.Ajax": [],
  "Ext.Component": [],
  "Ext.ComponentLoader": [],
  "Ext.ComponentManager": [
    "Ext.ComponentMgr"
  ],
  "Ext.ComponentQuery": [],
  "Ext.Editor": [],
  "Ext.ElementLoader": [],
  "Ext.FocusManager": [
    "Ext.FocusMgr"
  ],
  "Ext.Img": [],
  "Ext.LoadMask": [],
  "Ext.ModelManager": [
    "Ext.ModelMgr"
  ],
  "Ext.PluginManager": [
    "Ext.PluginMgr"
  ],
  "Ext.ProgressBar": [],
  "Ext.Queryable": [],
  "Ext.Shadow": [],
  "Ext.ShadowPool": [],
  "Ext.ZIndexManager": [
    "Ext.WindowGroup"
  ],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.EventBus": [],
  "Ext.app.EventDomain": [],
  "Ext.app.domain.Component": [],
  "Ext.app.domain.Controller": [],
  "Ext.app.domain.Direct": [],
  "Ext.app.domain.Global": [],
  "Ext.app.domain.Store": [],
  "Ext.button.Button": [
    "Ext.Button"
  ],
  "Ext.button.Cycle": [
    "Ext.CycleButton"
  ],
  "Ext.button.Manager": [
    "Ext.ButtonToggleManager"
  ],
  "Ext.button.Split": [
    "Ext.SplitButton"
  ],
  "Ext.chart.Callout": [],
  "Ext.chart.Chart": [],
  "Ext.chart.Highlight": [],
  "Ext.chart.Label": [],
  "Ext.chart.Legend": [],
  "Ext.chart.LegendItem": [],
  "Ext.chart.Mask": [],
  "Ext.chart.MaskLayer": [],
  "Ext.chart.Navigation": [],
  "Ext.chart.Shape": [],
  "Ext.chart.Tip": [],
  "Ext.chart.TipSurface": [],
  "Ext.chart.axis.Abstract": [],
  "Ext.chart.axis.Axis": [
    "Ext.chart.Axis"
  ],
  "Ext.chart.axis.Category": [
    "Ext.chart.CategoryAxis"
  ],
  "Ext.chart.axis.Gauge": [],
  "Ext.chart.axis.Numeric": [
    "Ext.chart.NumericAxis"
  ],
  "Ext.chart.axis.Radial": [],
  "Ext.chart.axis.Time": [
    "Ext.chart.TimeAxis"
  ],
  "Ext.chart.series.Area": [],
  "Ext.chart.series.Bar": [
    "Ext.chart.BarSeries",
    "Ext.chart.BarChart",
    "Ext.chart.StackedBarChart"
  ],
  "Ext.chart.series.Cartesian": [
    "Ext.chart.CartesianSeries",
    "Ext.chart.CartesianChart"
  ],
  "Ext.chart.series.Column": [
    "Ext.chart.ColumnSeries",
    "Ext.chart.ColumnChart",
    "Ext.chart.StackedColumnChart"
  ],
  "Ext.chart.series.Gauge": [],
  "Ext.chart.series.Line": [
    "Ext.chart.LineSeries",
    "Ext.chart.LineChart"
  ],
  "Ext.chart.series.Pie": [
    "Ext.chart.PieSeries",
    "Ext.chart.PieChart"
  ],
  "Ext.chart.series.Radar": [],
  "Ext.chart.series.Scatter": [],
  "Ext.chart.series.Series": [],
  "Ext.chart.theme.Base": [],
  "Ext.chart.theme.Theme": [],
  "Ext.container.AbstractContainer": [],
  "Ext.container.ButtonGroup": [
    "Ext.ButtonGroup"
  ],
  "Ext.container.Container": [
    "Ext.Container"
  ],
  "Ext.container.DockingContainer": [],
  "Ext.container.Monitor": [],
  "Ext.container.Viewport": [
    "Ext.Viewport"
  ],
  "Ext.data.AbstractStore": [],
  "Ext.data.ArrayStore": [],
  "Ext.data.Batch": [],
  "Ext.data.BufferStore": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [],
  "Ext.data.Group": [],
  "Ext.data.IdGenerator": [],
  "Ext.data.JsonP": [],
  "Ext.data.JsonPStore": [],
  "Ext.data.JsonStore": [],
  "Ext.data.Model": [
    "Ext.data.Record"
  ],
  "Ext.data.NodeInterface": [],
  "Ext.data.NodeStore": [],
  "Ext.data.Operation": [],
  "Ext.data.PageMap": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SequentialIdGenerator": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [],
  "Ext.data.StoreManager": [
    "Ext.StoreMgr",
    "Ext.data.StoreMgr",
    "Ext.StoreManager"
  ],
  "Ext.data.Tree": [],
  "Ext.data.TreeModel": [],
  "Ext.data.TreeStore": [],
  "Ext.data.Types": [],
  "Ext.data.UuidGenerator": [],
  "Ext.data.XmlStore": [],
  "Ext.data.association.Association": [
    "Ext.data.Association"
  ],
  "Ext.data.association.BelongsTo": [
    "Ext.data.BelongsToAssociation"
  ],
  "Ext.data.association.HasMany": [
    "Ext.data.HasManyAssociation"
  ],
  "Ext.data.association.HasOne": [
    "Ext.data.HasOneAssociation"
  ],
  "Ext.data.flash.BinaryXhr": [],
  "Ext.data.proxy.Ajax": [
    "Ext.data.HttpProxy",
    "Ext.data.AjaxProxy"
  ],
  "Ext.data.proxy.Client": [
    "Ext.data.ClientProxy"
  ],
  "Ext.data.proxy.Direct": [
    "Ext.data.DirectProxy"
  ],
  "Ext.data.proxy.JsonP": [
    "Ext.data.ScriptTagProxy"
  ],
  "Ext.data.proxy.LocalStorage": [
    "Ext.data.LocalStorageProxy"
  ],
  "Ext.data.proxy.Memory": [
    "Ext.data.MemoryProxy"
  ],
  "Ext.data.proxy.Proxy": [
    "Ext.data.DataProxy",
    "Ext.data.Proxy"
  ],
  "Ext.data.proxy.Rest": [
    "Ext.data.RestProxy"
  ],
  "Ext.data.proxy.Server": [
    "Ext.data.ServerProxy"
  ],
  "Ext.data.proxy.SessionStorage": [
    "Ext.data.SessionStorageProxy"
  ],
  "Ext.data.proxy.WebStorage": [
    "Ext.data.WebStorageProxy"
  ],
  "Ext.data.reader.Array": [
    "Ext.data.ArrayReader"
  ],
  "Ext.data.reader.Json": [
    "Ext.data.JsonReader"
  ],
  "Ext.data.reader.Reader": [
    "Ext.data.Reader",
    "Ext.data.DataReader"
  ],
  "Ext.data.reader.Xml": [
    "Ext.data.XmlReader"
  ],
  "Ext.data.validations": [],
  "Ext.data.writer.Json": [
    "Ext.data.JsonWriter"
  ],
  "Ext.data.writer.Writer": [
    "Ext.data.DataWriter",
    "Ext.data.Writer"
  ],
  "Ext.data.writer.Xml": [
    "Ext.data.XmlWriter"
  ],
  "Ext.dd.DD": [],
  "Ext.dd.DDProxy": [],
  "Ext.dd.DDTarget": [],
  "Ext.dd.DragDrop": [],
  "Ext.dd.DragDropManager": [
    "Ext.dd.DragDropMgr",
    "Ext.dd.DDM"
  ],
  "Ext.dd.DragSource": [],
  "Ext.dd.DragTracker": [],
  "Ext.dd.DragZone": [],
  "Ext.dd.DropTarget": [],
  "Ext.dd.DropZone": [],
  "Ext.dd.Registry": [],
  "Ext.dd.ScrollManager": [],
  "Ext.dd.StatusProxy": [],
  "Ext.diag.layout.Context": [],
  "Ext.diag.layout.ContextItem": [],
  "Ext.direct.Event": [],
  "Ext.direct.ExceptionEvent": [],
  "Ext.direct.JsonProvider": [],
  "Ext.direct.Manager": [],
  "Ext.direct.PollingProvider": [],
  "Ext.direct.Provider": [],
  "Ext.direct.RemotingEvent": [],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [],
  "Ext.direct.Transaction": [
    "Ext.Direct.Transaction"
  ],
  "Ext.dom.Layer": [
    "Ext.Layer"
  ],
  "Ext.draw.Color": [],
  "Ext.draw.Component": [],
  "Ext.draw.CompositeSprite": [],
  "Ext.draw.Draw": [],
  "Ext.draw.Matrix": [],
  "Ext.draw.Sprite": [],
  "Ext.draw.SpriteDD": [],
  "Ext.draw.Surface": [],
  "Ext.draw.Text": [],
  "Ext.draw.engine.ImageExporter": [],
  "Ext.draw.engine.Svg": [],
  "Ext.draw.engine.SvgExporter": [],
  "Ext.draw.engine.Vml": [],
  "Ext.flash.Component": [
    "Ext.FlashComponent"
  ],
  "Ext.form.Basic": [
    "Ext.form.BasicForm"
  ],
  "Ext.form.CheckboxGroup": [],
  "Ext.form.CheckboxManager": [],
  "Ext.form.FieldAncestor": [],
  "Ext.form.FieldContainer": [],
  "Ext.form.FieldSet": [],
  "Ext.form.Label": [],
  "Ext.form.Labelable": [],
  "Ext.form.Panel": [
    "Ext.FormPanel",
    "Ext.form.FormPanel"
  ],
  "Ext.form.RadioGroup": [],
  "Ext.form.RadioManager": [],
  "Ext.form.action.Action": [
    "Ext.form.Action"
  ],
  "Ext.form.action.DirectLoad": [
    "Ext.form.Action.DirectLoad"
  ],
  "Ext.form.action.DirectSubmit": [
    "Ext.form.Action.DirectSubmit"
  ],
  "Ext.form.action.Load": [
    "Ext.form.Action.Load"
  ],
  "Ext.form.action.StandardSubmit": [],
  "Ext.form.action.Submit": [
    "Ext.form.Action.Submit"
  ],
  "Ext.form.field.Base": [
    "Ext.form.Field",
    "Ext.form.BaseField"
  ],
  "Ext.form.field.Checkbox": [
    "Ext.form.Checkbox"
  ],
  "Ext.form.field.ComboBox": [
    "Ext.form.ComboBox"
  ],
  "Ext.form.field.Date": [
    "Ext.form.DateField",
    "Ext.form.Date"
  ],
  "Ext.form.field.Display": [
    "Ext.form.DisplayField",
    "Ext.form.Display"
  ],
  "Ext.form.field.Field": [],
  "Ext.form.field.File": [
    "Ext.form.FileUploadField",
    "Ext.ux.form.FileUploadField",
    "Ext.form.File"
  ],
  "Ext.form.field.FileButton": [],
  "Ext.form.field.Hidden": [
    "Ext.form.Hidden"
  ],
  "Ext.form.field.HtmlEditor": [
    "Ext.form.HtmlEditor"
  ],
  "Ext.form.field.Number": [
    "Ext.form.NumberField",
    "Ext.form.Number"
  ],
  "Ext.form.field.Picker": [
    "Ext.form.Picker"
  ],
  "Ext.form.field.Radio": [
    "Ext.form.Radio"
  ],
  "Ext.form.field.Spinner": [
    "Ext.form.Spinner"
  ],
  "Ext.form.field.Text": [
    "Ext.form.TextField",
    "Ext.form.Text"
  ],
  "Ext.form.field.TextArea": [
    "Ext.form.TextArea"
  ],
  "Ext.form.field.Time": [
    "Ext.form.TimeField",
    "Ext.form.Time"
  ],
  "Ext.form.field.Trigger": [
    "Ext.form.TriggerField",
    "Ext.form.TwinTriggerField",
    "Ext.form.Trigger"
  ],
  "Ext.form.field.VTypes": [
    "Ext.form.VTypes"
  ],
  "Ext.fx.Anim": [],
  "Ext.fx.Animator": [],
  "Ext.fx.CubicBezier": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Manager": [],
  "Ext.fx.PropertyHandler": [],
  "Ext.fx.Queue": [],
  "Ext.fx.target.Component": [],
  "Ext.fx.target.CompositeElement": [],
  "Ext.fx.target.CompositeElementCSS": [],
  "Ext.fx.target.CompositeSprite": [],
  "Ext.fx.target.Element": [],
  "Ext.fx.target.ElementCSS": [],
  "Ext.fx.target.Sprite": [],
  "Ext.fx.target.Target": [],
  "Ext.grid.CellContext": [],
  "Ext.grid.CellEditor": [],
  "Ext.grid.ColumnComponentLayout": [],
  "Ext.grid.ColumnLayout": [],
  "Ext.grid.ColumnManager": [
    "Ext.grid.ColumnModel"
  ],
  "Ext.grid.Panel": [
    "Ext.list.ListView",
    "Ext.ListView",
    "Ext.grid.GridPanel"
  ],
  "Ext.grid.RowEditor": [],
  "Ext.grid.RowEditorButtons": [],
  "Ext.grid.View": [],
  "Ext.grid.ViewDropZone": [],
  "Ext.grid.column.Action": [
    "Ext.grid.ActionColumn"
  ],
  "Ext.grid.column.Boolean": [
    "Ext.grid.BooleanColumn"
  ],
  "Ext.grid.column.CheckColumn": [
    "Ext.ux.CheckColumn"
  ],
  "Ext.grid.column.Column": [
    "Ext.grid.Column"
  ],
  "Ext.grid.column.Date": [
    "Ext.grid.DateColumn"
  ],
  "Ext.grid.column.Number": [
    "Ext.grid.NumberColumn"
  ],
  "Ext.grid.column.RowNumberer": [
    "Ext.grid.RowNumberer"
  ],
  "Ext.grid.column.Template": [
    "Ext.grid.TemplateColumn"
  ],
  "Ext.grid.feature.AbstractSummary": [],
  "Ext.grid.feature.Feature": [],
  "Ext.grid.feature.GroupStore": [],
  "Ext.grid.feature.Grouping": [],
  "Ext.grid.feature.GroupingSummary": [],
  "Ext.grid.feature.RowBody": [],
  "Ext.grid.feature.RowWrap": [],
  "Ext.grid.feature.Summary": [],
  "Ext.grid.header.Container": [],
  "Ext.grid.header.DragZone": [],
  "Ext.grid.header.DropZone": [],
  "Ext.grid.locking.HeaderContainer": [],
  "Ext.grid.locking.Lockable": [
    "Ext.grid.Lockable"
  ],
  "Ext.grid.locking.View": [
    "Ext.grid.LockingView"
  ],
  "Ext.grid.plugin.BufferedRenderer": [],
  "Ext.grid.plugin.BufferedRendererTableView": [],
  "Ext.grid.plugin.BufferedRendererTreeView": [],
  "Ext.grid.plugin.CellEditing": [],
  "Ext.grid.plugin.DivRenderer": [],
  "Ext.grid.plugin.DragDrop": [],
  "Ext.grid.plugin.Editing": [],
  "Ext.grid.plugin.HeaderReorderer": [],
  "Ext.grid.plugin.HeaderResizer": [],
  "Ext.grid.plugin.RowEditing": [],
  "Ext.grid.plugin.RowExpander": [],
  "Ext.grid.property.Grid": [
    "Ext.grid.PropertyGrid"
  ],
  "Ext.grid.property.HeaderContainer": [
    "Ext.grid.PropertyColumnModel"
  ],
  "Ext.grid.property.Property": [
    "Ext.PropGridProperty"
  ],
  "Ext.grid.property.Store": [
    "Ext.grid.PropertyStore"
  ],
  "Ext.layout.ClassList": [],
  "Ext.layout.Context": [],
  "Ext.layout.ContextItem": [],
  "Ext.layout.Layout": [],
  "Ext.layout.SizeModel": [],
  "Ext.layout.component.Auto": [],
  "Ext.layout.component.Body": [],
  "Ext.layout.component.BoundList": [],
  "Ext.layout.component.Button": [],
  "Ext.layout.component.Component": [],
  "Ext.layout.component.Dock": [
    "Ext.layout.component.AbstractDock"
  ],
  "Ext.layout.component.Draw": [],
  "Ext.layout.component.FieldSet": [],
  "Ext.layout.component.ProgressBar": [],
  "Ext.layout.component.field.ComboBox": [],
  "Ext.layout.component.field.Field": [],
  "Ext.layout.component.field.FieldContainer": [],
  "Ext.layout.component.field.HtmlEditor": [],
  "Ext.layout.component.field.Slider": [],
  "Ext.layout.component.field.Text": [],
  "Ext.layout.component.field.TextArea": [],
  "Ext.layout.component.field.Trigger": [],
  "Ext.layout.container.Absolute": [
    "Ext.layout.AbsoluteLayout"
  ],
  "Ext.layout.container.Accordion": [
    "Ext.layout.AccordionLayout"
  ],
  "Ext.layout.container.Anchor": [
    "Ext.layout.AnchorLayout"
  ],
  "Ext.layout.container.Auto": [],
  "Ext.layout.container.Border": [
    "Ext.layout.BorderLayout"
  ],
  "Ext.layout.container.Box": [
    "Ext.layout.BoxLayout"
  ],
  "Ext.layout.container.Card": [
    "Ext.layout.CardLayout"
  ],
  "Ext.layout.container.CheckboxGroup": [],
  "Ext.layout.container.Column": [
    "Ext.layout.ColumnLayout"
  ],
  "Ext.layout.container.Container": [
    "Ext.layout.ContainerLayout"
  ],
  "Ext.layout.container.Editor": [],
  "Ext.layout.container.Fit": [
    "Ext.layout.FitLayout"
  ],
  "Ext.layout.container.Form": [
    "Ext.layout.FormLayout"
  ],
  "Ext.layout.container.HBox": [
    "Ext.layout.HBoxLayout"
  ],
  "Ext.layout.container.Table": [
    "Ext.layout.TableLayout"
  ],
  "Ext.layout.container.VBox": [
    "Ext.layout.VBoxLayout"
  ],
  "Ext.layout.container.border.Region": [],
  "Ext.layout.container.boxOverflow.Menu": [
    "Ext.layout.boxOverflow.Menu"
  ],
  "Ext.layout.container.boxOverflow.None": [
    "Ext.layout.boxOverflow.None"
  ],
  "Ext.layout.container.boxOverflow.Scroller": [
    "Ext.layout.boxOverflow.Scroller"
  ],
  "Ext.menu.CheckItem": [],
  "Ext.menu.ColorPicker": [],
  "Ext.menu.DatePicker": [],
  "Ext.menu.Item": [
    "Ext.menu.TextItem"
  ],
  "Ext.menu.KeyNav": [],
  "Ext.menu.Manager": [
    "Ext.menu.MenuMgr"
  ],
  "Ext.menu.Menu": [],
  "Ext.menu.Separator": [],
  "Ext.panel.AbstractPanel": [],
  "Ext.panel.DD": [],
  "Ext.panel.Header": [],
  "Ext.panel.Panel": [
    "Ext.Panel"
  ],
  "Ext.panel.Proxy": [
    "Ext.dd.PanelProxy"
  ],
  "Ext.panel.Table": [],
  "Ext.panel.Tool": [],
  "Ext.picker.Color": [
    "Ext.ColorPalette"
  ],
  "Ext.picker.Date": [
    "Ext.DatePicker"
  ],
  "Ext.picker.Month": [
    "Ext.MonthPicker"
  ],
  "Ext.picker.Time": [],
  "Ext.resizer.BorderSplitter": [],
  "Ext.resizer.BorderSplitterTracker": [],
  "Ext.resizer.Handle": [],
  "Ext.resizer.ResizeTracker": [],
  "Ext.resizer.Resizer": [
    "Ext.Resizable"
  ],
  "Ext.resizer.Splitter": [],
  "Ext.resizer.SplitterTracker": [],
  "Ext.rtl.AbstractComponent": [],
  "Ext.rtl.EventObjectImpl": [],
  "Ext.rtl.button.Button": [],
  "Ext.rtl.dd.DD": [],
  "Ext.rtl.dom.Element_anim": [],
  "Ext.rtl.dom.Element_insertion": [],
  "Ext.rtl.dom.Element_position": [],
  "Ext.rtl.dom.Element_scroll": [],
  "Ext.rtl.dom.Element_static": [],
  "Ext.rtl.dom.Layer": [],
  "Ext.rtl.form.field.Checkbox": [],
  "Ext.rtl.form.field.File": [],
  "Ext.rtl.form.field.Spinner": [],
  "Ext.rtl.form.field.Trigger": [],
  "Ext.rtl.grid.CellEditor": [],
  "Ext.rtl.grid.RowEditor": [],
  "Ext.rtl.grid.column.Column": [],
  "Ext.rtl.grid.plugin.HeaderResizer": [],
  "Ext.rtl.grid.plugin.RowEditing": [],
  "Ext.rtl.layout.ContextItem": [],
  "Ext.rtl.layout.component.Dock": [],
  "Ext.rtl.layout.component.field.Text": [],
  "Ext.rtl.layout.component.field.Trigger": [],
  "Ext.rtl.layout.container.Absolute": [],
  "Ext.rtl.layout.container.Border": [],
  "Ext.rtl.layout.container.Box": [],
  "Ext.rtl.layout.container.CheckboxGroup": [],
  "Ext.rtl.layout.container.Column": [],
  "Ext.rtl.layout.container.HBox": [],
  "Ext.rtl.layout.container.VBox": [],
  "Ext.rtl.layout.container.boxOverflow.Menu": [],
  "Ext.rtl.layout.container.boxOverflow.Scroller": [],
  "Ext.rtl.panel.Header": [],
  "Ext.rtl.panel.Panel": [],
  "Ext.rtl.resizer.BorderSplitterTracker": [],
  "Ext.rtl.resizer.ResizeTracker": [],
  "Ext.rtl.resizer.SplitterTracker": [],
  "Ext.rtl.selection.CellModel": [],
  "Ext.rtl.selection.TreeModel": [],
  "Ext.rtl.slider.Multi": [],
  "Ext.rtl.tab.Bar": [],
  "Ext.rtl.tip.QuickTipManager": [],
  "Ext.rtl.tree.Column": [],
  "Ext.rtl.util.Floating": [],
  "Ext.rtl.util.Renderable": [],
  "Ext.rtl.view.Table": [],
  "Ext.selection.CellModel": [],
  "Ext.selection.CheckboxModel": [],
  "Ext.selection.DataViewModel": [],
  "Ext.selection.Model": [
    "Ext.AbstractSelectionModel"
  ],
  "Ext.selection.RowModel": [],
  "Ext.selection.TreeModel": [],
  "Ext.slider.Multi": [
    "Ext.slider.MultiSlider"
  ],
  "Ext.slider.Single": [
    "Ext.Slider",
    "Ext.form.SliderField",
    "Ext.slider.SingleSlider",
    "Ext.slider.Slider"
  ],
  "Ext.slider.Thumb": [],
  "Ext.slider.Tip": [],
  "Ext.state.CookieProvider": [],
  "Ext.state.LocalStorageProvider": [],
  "Ext.state.Manager": [],
  "Ext.state.Provider": [],
  "Ext.state.Stateful": [],
  "Ext.tab.Bar": [],
  "Ext.tab.Panel": [
    "Ext.TabPanel"
  ],
  "Ext.tab.Tab": [],
  "Ext.tip.QuickTip": [
    "Ext.QuickTip"
  ],
  "Ext.tip.QuickTipManager": [
    "Ext.QuickTips"
  ],
  "Ext.tip.Tip": [
    "Ext.Tip"
  ],
  "Ext.tip.ToolTip": [
    "Ext.ToolTip"
  ],
  "Ext.toolbar.Fill": [
    "Ext.Toolbar.Fill"
  ],
  "Ext.toolbar.Item": [
    "Ext.Toolbar.Item"
  ],
  "Ext.toolbar.Paging": [
    "Ext.PagingToolbar"
  ],
  "Ext.toolbar.Separator": [
    "Ext.Toolbar.Separator"
  ],
  "Ext.toolbar.Spacer": [
    "Ext.Toolbar.Spacer"
  ],
  "Ext.toolbar.TextItem": [
    "Ext.Toolbar.TextItem"
  ],
  "Ext.toolbar.Toolbar": [
    "Ext.Toolbar"
  ],
  "Ext.tree.Column": [],
  "Ext.tree.Panel": [
    "Ext.tree.TreePanel",
    "Ext.TreePanel"
  ],
  "Ext.tree.View": [],
  "Ext.tree.ViewDragZone": [],
  "Ext.tree.ViewDropZone": [],
  "Ext.tree.plugin.TreeViewDragDrop": [],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Animate": [],
  "Ext.util.Bindable": [],
  "Ext.util.CSS": [],
  "Ext.util.ClickRepeater": [],
  "Ext.util.ComponentDragger": [],
  "Ext.util.Cookies": [],
  "Ext.util.ElementContainer": [],
  "Ext.util.Filter": [],
  "Ext.util.Floating": [],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.History": [
    "Ext.History"
  ],
  "Ext.util.Inflector": [],
  "Ext.util.KeyMap": [
    "Ext.KeyMap"
  ],
  "Ext.util.KeyNav": [
    "Ext.KeyNav"
  ],
  "Ext.util.LruCache": [],
  "Ext.util.Memento": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.Point": [],
  "Ext.util.ProtoElement": [],
  "Ext.util.Queue": [],
  "Ext.util.Region": [],
  "Ext.util.Renderable": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TextMetrics": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.ComboTriggerWindow": [],
  "Ext.ux.CropWindow": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.GMapPanel": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.GroupTabRenderer": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.ImageCrop": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.PagingToolbarResizer": [],
  "Ext.ux.PreviewPlugin": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.TabCloseMenu": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.TreeFilter": [],
  "Ext.ux.TreePicker": [],
  "Ext.ux.TreeTiggerWindow": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.form.MultiComboBox": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.form.field.BoxSelect": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.layout.Center": [],
  "Ext.ux.layout.component.field.BoxSelectField": [],
  "Ext.ux.oa.WorkFlow": [],
  "Ext.ux.oa.WorkFlowPanel": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.uploadPanel.ImageUploadCropPanel": [],
  "Ext.ux.uploadPanel.UploadPanel": [],
  "Ext.view.AbstractView": [],
  "Ext.view.BoundList": [
    "Ext.BoundList"
  ],
  "Ext.view.BoundListKeyNav": [],
  "Ext.view.DragZone": [],
  "Ext.view.DropZone": [],
  "Ext.view.NodeCache": [],
  "Ext.view.Table": [],
  "Ext.view.TableLayout": [],
  "Ext.view.View": [
    "Ext.DataView"
  ],
  "Ext.window.MessageBox": [],
  "Ext.window.Window": [
    "Ext.Window"
  ],
  "Overrides.Number": [],
  "Overrides.data.Model": [],
  "Overrides.form.Basic": [],
  "Overrides.form.VTypes": [],
  "Overrides.form.field.Base": [],
  "Overrides.form.field.ComboBox": [],
  "Overrides.form.field.DisplayField": [],
  "Wenjoy.Application": [],
  "Wenjoy.controller.Base": [],
  "Wenjoy.controller.creditsdetail.CreditsDetail": [],
  "Wenjoy.controller.creditsdetail.SalesCommissionRule": [],
  "Wenjoy.controller.creditsdetail.TeamCommissionsRule": [],
  "Wenjoy.controller.customer.Customer": [],
  "Wenjoy.controller.dictdata.DictData": [],
  "Wenjoy.controller.dictdata.DictType": [],
  "Wenjoy.controller.doc.AppHelp": [],
  "Wenjoy.controller.inf.Message": [],
  "Wenjoy.controller.menu.Menu": [],
  "Wenjoy.controller.oa.CreditsExchange": [],
  "Wenjoy.controller.order.Order": [],
  "Wenjoy.controller.product.Product": [],
  "Wenjoy.controller.product.ProductLimit": [],
  "Wenjoy.controller.product.ProductType": [],
  "Wenjoy.controller.product.PublicProductApply": [],
  "Wenjoy.controller.product.Supplier": [],
  "Wenjoy.controller.role.Permission": [],
  "Wenjoy.controller.role.Role": [],
  "Wenjoy.controller.role.RoleType": [],
  "Wenjoy.controller.user.Agent": [],
  "Wenjoy.controller.user.Dept": [],
  "Wenjoy.controller.user.EvaluationType": [],
  "Wenjoy.controller.user.PositionLevel": [],
  "Wenjoy.controller.user.User": [],
  "Wenjoy.model.attachment.Attachment": [],
  "Wenjoy.model.creditsdetail.CreditsDetail": [],
  "Wenjoy.model.creditsdetail.SalesCommissionRule": [],
  "Wenjoy.model.creditsdetail.TeamCommissionsRule": [],
  "Wenjoy.model.customer.Contact": [],
  "Wenjoy.model.customer.Customer": [],
  "Wenjoy.model.dictdata.DictData": [],
  "Wenjoy.model.dictdata.DictType": [],
  "Wenjoy.model.doc.ApplicationHelper": [],
  "Wenjoy.model.inf.Message": [],
  "Wenjoy.model.inf.MessageReceive": [],
  "Wenjoy.model.menu.MenuTree": [],
  "Wenjoy.model.oa.CreditsExchange": [],
  "Wenjoy.model.order.Order": [],
  "Wenjoy.model.product.Product": [],
  "Wenjoy.model.product.ProductLimit": [],
  "Wenjoy.model.product.ProductType": [],
  "Wenjoy.model.product.ProductYieldRate": [],
  "Wenjoy.model.product.PublicProductApply": [],
  "Wenjoy.model.product.Supplier": [],
  "Wenjoy.model.role.Permission": [],
  "Wenjoy.model.role.Role": [],
  "Wenjoy.model.role.RoleBelongUser": [],
  "Wenjoy.model.role.RoleType": [],
  "Wenjoy.model.update.UpdateLog": [],
  "Wenjoy.model.user.Agent": [],
  "Wenjoy.model.user.DeptTree": [],
  "Wenjoy.model.user.EvaluationType": [],
  "Wenjoy.model.user.PositionLevel": [],
  "Wenjoy.model.user.User": [],
  "Wenjoy.store.attachment.Attachment": [],
  "Wenjoy.store.chart.DailyRaiseProgress": [],
  "Wenjoy.store.combo.Agent": [],
  "Wenjoy.store.combo.ApproveStateType": [],
  "Wenjoy.store.combo.CertificateType": [],
  "Wenjoy.store.combo.ComUser": [],
  "Wenjoy.store.combo.ComboDept": [],
  "Wenjoy.store.combo.ComboEvaluationtype": [],
  "Wenjoy.store.combo.ComboPositionLeveal": [],
  "Wenjoy.store.combo.ContractStateType": [],
  "Wenjoy.store.combo.CredetailSource": [],
  "Wenjoy.store.combo.CredetailState": [],
  "Wenjoy.store.combo.CredetailUserType": [],
  "Wenjoy.store.combo.CustomerDetail": [],
  "Wenjoy.store.combo.CustomerLevel": [],
  "Wenjoy.store.combo.CustomerSource": [],
  "Wenjoy.store.combo.CustomerType": [],
  "Wenjoy.store.combo.DictType": [],
  "Wenjoy.store.combo.MarriagedState": [],
  "Wenjoy.store.combo.NationType": [],
  "Wenjoy.store.combo.OrderDetail": [],
  "Wenjoy.store.combo.OrderSourceType": [],
  "Wenjoy.store.combo.OrderStateType": [],
  "Wenjoy.store.combo.Permission": [],
  "Wenjoy.store.combo.PoliticalStatusType": [],
  "Wenjoy.store.combo.ProCreditPromotionMeasures": [],
  "Wenjoy.store.combo.ProEarningAssign": [],
  "Wenjoy.store.combo.ProFundUse": [],
  "Wenjoy.store.combo.ProProjectLocation": [],
  "Wenjoy.store.combo.ProPublishState": [],
  "Wenjoy.store.combo.ProStateList": [],
  "Wenjoy.store.combo.ProTerm": [],
  "Wenjoy.store.combo.ProductDetail": [],
  "Wenjoy.store.combo.ProductType": [],
  "Wenjoy.store.combo.PublishProductState": [],
  "Wenjoy.store.combo.RoleType": [],
  "Wenjoy.store.combo.SectorType": [],
  "Wenjoy.store.combo.SexType": [],
  "Wenjoy.store.combo.StaffStateType": [],
  "Wenjoy.store.combo.StaffType": [],
  "Wenjoy.store.combo.StockholderBackgroundType": [],
  "Wenjoy.store.combo.Supplier": [],
  "Wenjoy.store.combo.SupplierType": [],
  "Wenjoy.store.creditsdetail.CreditsDetail": [],
  "Wenjoy.store.creditsdetail.SalesCommissionRule": [],
  "Wenjoy.store.creditsdetail.TeamCommissionsRule": [],
  "Wenjoy.store.customer.Contact": [],
  "Wenjoy.store.customer.Customer": [],
  "Wenjoy.store.dictdata.DictData": [],
  "Wenjoy.store.dictdata.DictType": [],
  "Wenjoy.store.inf.Message": [],
  "Wenjoy.store.inf.MessageReceive": [],
  "Wenjoy.store.menu.MenuPermission": [],
  "Wenjoy.store.menu.MenuTree": [],
  "Wenjoy.store.oa.CreditsExchange": [],
  "Wenjoy.store.oa.ProcessActivitiGraph": [],
  "Wenjoy.store.order.Order": [],
  "Wenjoy.store.product.Product": [],
  "Wenjoy.store.product.ProductLimit": [],
  "Wenjoy.store.product.ProductType": [],
  "Wenjoy.store.product.ProductYieldRate": [],
  "Wenjoy.store.product.PublicProductApply": [],
  "Wenjoy.store.product.Supplier": [],
  "Wenjoy.store.role.ByPermissionIdGetRole": [],
  "Wenjoy.store.role.ByRoleIdGetPermission": [],
  "Wenjoy.store.role.ByRoleTypeIdGetRole": [],
  "Wenjoy.store.role.Permission": [],
  "Wenjoy.store.role.Role": [],
  "Wenjoy.store.role.RoleBelongUser": [],
  "Wenjoy.store.role.RoleType": [],
  "Wenjoy.store.role.UserBelongPermission": [],
  "Wenjoy.store.role.UserBelongRole": [],
  "Wenjoy.store.update.UpdateLog": [],
  "Wenjoy.store.user.Agent": [],
  "Wenjoy.store.user.DeptTree": [],
  "Wenjoy.store.user.EvaluationType": [],
  "Wenjoy.store.user.PositionLevel": [],
  "Wenjoy.store.user.User": [],
  "Wenjoy.view.CenterPanel": [],
  "Wenjoy.view.LeftMenu": [],
  "Wenjoy.view.TopPanel": [],
  "Wenjoy.view.Viewport": [],
  "Wenjoy.view.chart.DailyRaiseProgressLineChart": [],
  "Wenjoy.view.chart.UploadExcel": [],
  "Wenjoy.view.common.AttachmentUpload": [],
  "Wenjoy.view.common.ExcelImport": [],
  "Wenjoy.view.common.ExtKindEditor": [],
  "Wenjoy.view.common.ImageUpload": [],
  "Wenjoy.view.common.PermissionAdjust": [],
  "Wenjoy.view.common.PwdModify": [],
  "Wenjoy.view.common.RoleAdjust": [],
  "Wenjoy.view.common.UserAdjust": [],
  "Wenjoy.view.common.WorkFlowGraphWindow": [],
  "Wenjoy.view.creditsdetail.CreditsDetailDetail": [],
  "Wenjoy.view.creditsdetail.CreditsDetailEdit": [],
  "Wenjoy.view.creditsdetail.CreditsDetailList": [],
  "Wenjoy.view.creditsdetail.SalesCommissionRuleDetail": [],
  "Wenjoy.view.creditsdetail.SalesCommissionRuleEdit": [],
  "Wenjoy.view.creditsdetail.SalesCommissionRuleList": [],
  "Wenjoy.view.creditsdetail.TeamCommissionsRuleDetail": [],
  "Wenjoy.view.creditsdetail.TeamCommissionsRuleEdit": [],
  "Wenjoy.view.creditsdetail.TeamCommissionsRuleList": [],
  "Wenjoy.view.customer.ContactDetail": [],
  "Wenjoy.view.customer.ContactEdit": [],
  "Wenjoy.view.customer.CustomerDetail": [],
  "Wenjoy.view.customer.CustomerEdit": [],
  "Wenjoy.view.customer.CustomerList": [],
  "Wenjoy.view.dictdata.DictDataEdit": [],
  "Wenjoy.view.dictdata.DictDataList": [],
  "Wenjoy.view.dictdata.DictTypeEdit": [],
  "Wenjoy.view.dictdata.DictTypeList": [],
  "Wenjoy.view.doc.AppHelpIndex": [],
  "Wenjoy.view.doc.AppHelperDetail": [],
  "Wenjoy.view.doc.AppHelperMenuEdit": [],
  "Wenjoy.view.inf.MessageEdit": [],
  "Wenjoy.view.inf.MessageList": [],
  "Wenjoy.view.menu.Edit": [],
  "Wenjoy.view.menu.MenuTree": [],
  "Wenjoy.view.oa.CreditsExchangeDetail": [],
  "Wenjoy.view.oa.CreditsExchangeEdit": [],
  "Wenjoy.view.oa.CreditsExchangeList": [],
  "Wenjoy.view.order.AppendOrderList": [],
  "Wenjoy.view.order.OrderDeal": [],
  "Wenjoy.view.order.OrderEdit": [],
  "Wenjoy.view.order.OrderList": [],
  "Wenjoy.view.order.OrderMoneyAccount": [],
  "Wenjoy.view.order.OrderRemark": [],
  "Wenjoy.view.portlet.ChartPortlet": [],
  "Wenjoy.view.portlet.GridPortlet": [],
  "Wenjoy.view.portlet.PortalColumn": [],
  "Wenjoy.view.portlet.PortalDropZone": [],
  "Wenjoy.view.portlet.PortalPanel": [],
  "Wenjoy.view.portlet.Portlet": [],
  "Wenjoy.view.product.FeeRateList": [],
  "Wenjoy.view.product.ProductDetail": [],
  "Wenjoy.view.product.ProductEdit": [],
  "Wenjoy.view.product.ProductLimitEdit": [],
  "Wenjoy.view.product.ProductLimitList": [],
  "Wenjoy.view.product.ProductList": [],
  "Wenjoy.view.product.ProductRateOrSalesCommission": [],
  "Wenjoy.view.product.ProductTypeDetail": [],
  "Wenjoy.view.product.ProductTypeEdit": [],
  "Wenjoy.view.product.ProductTypeList": [],
  "Wenjoy.view.product.ProductYieldRateDetail": [],
  "Wenjoy.view.product.ProductYieldRateEdit": [],
  "Wenjoy.view.product.PublicProductApplyEdit": [],
  "Wenjoy.view.product.PublicProductApplyList": [],
  "Wenjoy.view.product.SalesCommissionList": [],
  "Wenjoy.view.product.SupplierDetail": [],
  "Wenjoy.view.product.SupplierEdit": [],
  "Wenjoy.view.product.SupplierList": [],
  "Wenjoy.view.role.PermissionDetail": [],
  "Wenjoy.view.role.PermissionEdit": [],
  "Wenjoy.view.role.PermissionList": [],
  "Wenjoy.view.role.PermissionSourceEdit": [],
  "Wenjoy.view.role.PermissionTable": [],
  "Wenjoy.view.role.RoleDetail": [],
  "Wenjoy.view.role.RoleEdit": [],
  "Wenjoy.view.role.RoleList": [],
  "Wenjoy.view.role.RoleTypeDetail": [],
  "Wenjoy.view.role.RoleTypeEdit": [],
  "Wenjoy.view.role.RoleTypeList": [],
  "Wenjoy.view.role.UserTable": [],
  "Wenjoy.view.user.AgentEdit": [],
  "Wenjoy.view.user.AgentList": [],
  "Wenjoy.view.user.DeptEdit": [],
  "Wenjoy.view.user.DeptTree": [],
  "Wenjoy.view.user.EvaluationTypeDetail": [],
  "Wenjoy.view.user.EvaluationTypeEdit": [],
  "Wenjoy.view.user.EvaluationTypeList": [],
  "Wenjoy.view.user.PositionLevelDetail": [],
  "Wenjoy.view.user.PositionLevelEdit": [],
  "Wenjoy.view.user.PositionLevelList": [],
  "Wenjoy.view.user.PositionLevelSourceEdit": [],
  "Wenjoy.view.user.ReferUserList": [],
  "Wenjoy.view.user.UserDetail": [],
  "Wenjoy.view.user.UserEdit": [],
  "Wenjoy.view.user.UserList": [],
  "account": []
});
Ext.ClassManager.addNameAliasMappings({
  "Common.permission.Permission": [
    "widget.permission"
  ],
  "Common.util.Config": [],
  "Common.util.Util": [],
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.Action": [],
  "Ext.Ajax": [],
  "Ext.Component": [
    "widget.box",
    "widget.component"
  ],
  "Ext.ComponentLoader": [],
  "Ext.ComponentManager": [],
  "Ext.ComponentQuery": [],
  "Ext.Editor": [
    "widget.editor"
  ],
  "Ext.ElementLoader": [],
  "Ext.FocusManager": [],
  "Ext.Img": [
    "widget.image",
    "widget.imagecomponent"
  ],
  "Ext.LoadMask": [
    "widget.loadmask"
  ],
  "Ext.ModelManager": [],
  "Ext.PluginManager": [],
  "Ext.ProgressBar": [
    "widget.progressbar"
  ],
  "Ext.Queryable": [],
  "Ext.Shadow": [],
  "Ext.ShadowPool": [],
  "Ext.ZIndexManager": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.EventBus": [],
  "Ext.app.EventDomain": [],
  "Ext.app.domain.Component": [],
  "Ext.app.domain.Controller": [],
  "Ext.app.domain.Direct": [],
  "Ext.app.domain.Global": [],
  "Ext.app.domain.Store": [],
  "Ext.button.Button": [
    "widget.button"
  ],
  "Ext.button.Cycle": [
    "widget.cycle"
  ],
  "Ext.button.Manager": [],
  "Ext.button.Split": [
    "widget.splitbutton"
  ],
  "Ext.chart.Callout": [],
  "Ext.chart.Chart": [
    "widget.chart"
  ],
  "Ext.chart.Highlight": [],
  "Ext.chart.Label": [],
  "Ext.chart.Legend": [],
  "Ext.chart.LegendItem": [],
  "Ext.chart.Mask": [],
  "Ext.chart.MaskLayer": [],
  "Ext.chart.Navigation": [],
  "Ext.chart.Shape": [],
  "Ext.chart.Tip": [],
  "Ext.chart.TipSurface": [],
  "Ext.chart.axis.Abstract": [],
  "Ext.chart.axis.Axis": [],
  "Ext.chart.axis.Category": [
    "axis.category"
  ],
  "Ext.chart.axis.Gauge": [
    "axis.gauge"
  ],
  "Ext.chart.axis.Numeric": [
    "axis.numeric"
  ],
  "Ext.chart.axis.Radial": [
    "axis.radial"
  ],
  "Ext.chart.axis.Time": [
    "axis.time"
  ],
  "Ext.chart.series.Area": [
    "series.area"
  ],
  "Ext.chart.series.Bar": [
    "series.bar"
  ],
  "Ext.chart.series.Cartesian": [],
  "Ext.chart.series.Column": [
    "series.column"
  ],
  "Ext.chart.series.Gauge": [
    "series.gauge"
  ],
  "Ext.chart.series.Line": [
    "series.line"
  ],
  "Ext.chart.series.Pie": [
    "series.pie"
  ],
  "Ext.chart.series.Radar": [
    "series.radar"
  ],
  "Ext.chart.series.Scatter": [
    "series.scatter"
  ],
  "Ext.chart.series.Series": [],
  "Ext.chart.theme.Base": [],
  "Ext.chart.theme.Theme": [],
  "Ext.container.AbstractContainer": [],
  "Ext.container.ButtonGroup": [
    "widget.buttongroup"
  ],
  "Ext.container.Container": [
    "widget.container"
  ],
  "Ext.container.DockingContainer": [],
  "Ext.container.Monitor": [],
  "Ext.container.Viewport": [
    "widget.viewport"
  ],
  "Ext.data.AbstractStore": [],
  "Ext.data.ArrayStore": [
    "store.array"
  ],
  "Ext.data.Batch": [],
  "Ext.data.BufferStore": [
    "store.buffer"
  ],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [
    "store.direct"
  ],
  "Ext.data.Errors": [],
  "Ext.data.Field": [
    "data.field"
  ],
  "Ext.data.Group": [],
  "Ext.data.IdGenerator": [],
  "Ext.data.JsonP": [],
  "Ext.data.JsonPStore": [
    "store.jsonp"
  ],
  "Ext.data.JsonStore": [
    "store.json"
  ],
  "Ext.data.Model": [],
  "Ext.data.NodeInterface": [],
  "Ext.data.NodeStore": [
    "store.node"
  ],
  "Ext.data.Operation": [],
  "Ext.data.PageMap": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SequentialIdGenerator": [
    "idgen.sequential"
  ],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [
    "store.store"
  ],
  "Ext.data.StoreManager": [],
  "Ext.data.Tree": [
    "data.tree"
  ],
  "Ext.data.TreeModel": [],
  "Ext.data.TreeStore": [
    "store.tree"
  ],
  "Ext.data.Types": [],
  "Ext.data.UuidGenerator": [
    "idgen.uuid"
  ],
  "Ext.data.XmlStore": [
    "store.xml"
  ],
  "Ext.data.association.Association": [],
  "Ext.data.association.BelongsTo": [
    "association.belongsto"
  ],
  "Ext.data.association.HasMany": [
    "association.hasmany"
  ],
  "Ext.data.association.HasOne": [
    "association.hasone"
  ],
  "Ext.data.flash.BinaryXhr": [],
  "Ext.data.proxy.Ajax": [
    "proxy.ajax"
  ],
  "Ext.data.proxy.Client": [],
  "Ext.data.proxy.Direct": [
    "proxy.direct"
  ],
  "Ext.data.proxy.JsonP": [
    "proxy.jsonp",
    "proxy.scripttag"
  ],
  "Ext.data.proxy.LocalStorage": [
    "proxy.localstorage"
  ],
  "Ext.data.proxy.Memory": [
    "proxy.memory"
  ],
  "Ext.data.proxy.Proxy": [
    "proxy.proxy"
  ],
  "Ext.data.proxy.Rest": [
    "proxy.rest"
  ],
  "Ext.data.proxy.Server": [
    "proxy.server"
  ],
  "Ext.data.proxy.SessionStorage": [
    "proxy.sessionstorage"
  ],
  "Ext.data.proxy.WebStorage": [],
  "Ext.data.reader.Array": [
    "reader.array"
  ],
  "Ext.data.reader.Json": [
    "reader.json"
  ],
  "Ext.data.reader.Reader": [],
  "Ext.data.reader.Xml": [
    "reader.xml"
  ],
  "Ext.data.validations": [],
  "Ext.data.writer.Json": [
    "writer.json"
  ],
  "Ext.data.writer.Writer": [
    "writer.base"
  ],
  "Ext.data.writer.Xml": [
    "writer.xml"
  ],
  "Ext.dd.DD": [],
  "Ext.dd.DDProxy": [],
  "Ext.dd.DDTarget": [],
  "Ext.dd.DragDrop": [],
  "Ext.dd.DragDropManager": [],
  "Ext.dd.DragSource": [],
  "Ext.dd.DragTracker": [],
  "Ext.dd.DragZone": [],
  "Ext.dd.DropTarget": [],
  "Ext.dd.DropZone": [],
  "Ext.dd.Registry": [],
  "Ext.dd.ScrollManager": [],
  "Ext.dd.StatusProxy": [],
  "Ext.diag.layout.Context": [],
  "Ext.diag.layout.ContextItem": [],
  "Ext.direct.Event": [
    "direct.event"
  ],
  "Ext.direct.ExceptionEvent": [
    "direct.exception"
  ],
  "Ext.direct.JsonProvider": [
    "direct.jsonprovider"
  ],
  "Ext.direct.Manager": [],
  "Ext.direct.PollingProvider": [
    "direct.pollingprovider"
  ],
  "Ext.direct.Provider": [
    "direct.provider"
  ],
  "Ext.direct.RemotingEvent": [
    "direct.rpc"
  ],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [
    "direct.remotingprovider"
  ],
  "Ext.direct.Transaction": [
    "direct.transaction"
  ],
  "Ext.dom.Layer": [],
  "Ext.draw.Color": [],
  "Ext.draw.Component": [
    "widget.draw"
  ],
  "Ext.draw.CompositeSprite": [],
  "Ext.draw.Draw": [],
  "Ext.draw.Matrix": [],
  "Ext.draw.Sprite": [],
  "Ext.draw.SpriteDD": [],
  "Ext.draw.Surface": [],
  "Ext.draw.Text": [
    "widget.text"
  ],
  "Ext.draw.engine.ImageExporter": [],
  "Ext.draw.engine.Svg": [],
  "Ext.draw.engine.SvgExporter": [],
  "Ext.draw.engine.Vml": [],
  "Ext.flash.Component": [
    "widget.flash"
  ],
  "Ext.form.Basic": [],
  "Ext.form.CheckboxGroup": [
    "widget.checkboxgroup"
  ],
  "Ext.form.CheckboxManager": [],
  "Ext.form.FieldAncestor": [],
  "Ext.form.FieldContainer": [
    "widget.fieldcontainer"
  ],
  "Ext.form.FieldSet": [
    "widget.fieldset"
  ],
  "Ext.form.Label": [
    "widget.label"
  ],
  "Ext.form.Labelable": [],
  "Ext.form.Panel": [
    "widget.form"
  ],
  "Ext.form.RadioGroup": [
    "widget.radiogroup"
  ],
  "Ext.form.RadioManager": [],
  "Ext.form.action.Action": [],
  "Ext.form.action.DirectLoad": [
    "formaction.directload"
  ],
  "Ext.form.action.DirectSubmit": [
    "formaction.directsubmit"
  ],
  "Ext.form.action.Load": [
    "formaction.load"
  ],
  "Ext.form.action.StandardSubmit": [
    "formaction.standardsubmit"
  ],
  "Ext.form.action.Submit": [
    "formaction.submit"
  ],
  "Ext.form.field.Base": [
    "widget.field"
  ],
  "Ext.form.field.Checkbox": [
    "widget.checkbox",
    "widget.checkboxfield"
  ],
  "Ext.form.field.ComboBox": [
    "widget.combo",
    "widget.combobox"
  ],
  "Ext.form.field.Date": [
    "widget.datefield"
  ],
  "Ext.form.field.Display": [
    "widget.displayfield"
  ],
  "Ext.form.field.Field": [],
  "Ext.form.field.File": [
    "widget.filefield",
    "widget.fileuploadfield"
  ],
  "Ext.form.field.FileButton": [
    "widget.filebutton"
  ],
  "Ext.form.field.Hidden": [
    "widget.hidden",
    "widget.hiddenfield"
  ],
  "Ext.form.field.HtmlEditor": [
    "widget.htmleditor"
  ],
  "Ext.form.field.Number": [
    "widget.numberfield"
  ],
  "Ext.form.field.Picker": [
    "widget.pickerfield"
  ],
  "Ext.form.field.Radio": [
    "widget.radio",
    "widget.radiofield"
  ],
  "Ext.form.field.Spinner": [
    "widget.spinnerfield"
  ],
  "Ext.form.field.Text": [
    "widget.textfield"
  ],
  "Ext.form.field.TextArea": [
    "widget.textarea",
    "widget.textareafield"
  ],
  "Ext.form.field.Time": [
    "widget.timefield"
  ],
  "Ext.form.field.Trigger": [
    "widget.trigger",
    "widget.triggerfield"
  ],
  "Ext.form.field.VTypes": [],
  "Ext.fx.Anim": [],
  "Ext.fx.Animator": [],
  "Ext.fx.CubicBezier": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Manager": [],
  "Ext.fx.PropertyHandler": [],
  "Ext.fx.Queue": [],
  "Ext.fx.target.Component": [],
  "Ext.fx.target.CompositeElement": [],
  "Ext.fx.target.CompositeElementCSS": [],
  "Ext.fx.target.CompositeSprite": [],
  "Ext.fx.target.Element": [],
  "Ext.fx.target.ElementCSS": [],
  "Ext.fx.target.Sprite": [],
  "Ext.fx.target.Target": [],
  "Ext.grid.CellContext": [],
  "Ext.grid.CellEditor": [],
  "Ext.grid.ColumnComponentLayout": [
    "layout.columncomponent"
  ],
  "Ext.grid.ColumnLayout": [
    "layout.gridcolumn"
  ],
  "Ext.grid.ColumnManager": [],
  "Ext.grid.Panel": [
    "widget.grid",
    "widget.gridpanel"
  ],
  "Ext.grid.RowEditor": [
    "widget.roweditor"
  ],
  "Ext.grid.RowEditorButtons": [
    "widget.roweditorbuttons"
  ],
  "Ext.grid.View": [
    "widget.gridview"
  ],
  "Ext.grid.ViewDropZone": [],
  "Ext.grid.column.Action": [
    "widget.actioncolumn"
  ],
  "Ext.grid.column.Boolean": [
    "widget.booleancolumn"
  ],
  "Ext.grid.column.CheckColumn": [
    "widget.checkcolumn"
  ],
  "Ext.grid.column.Column": [
    "widget.gridcolumn"
  ],
  "Ext.grid.column.Date": [
    "widget.datecolumn"
  ],
  "Ext.grid.column.Number": [
    "widget.numbercolumn"
  ],
  "Ext.grid.column.RowNumberer": [
    "widget.rownumberer"
  ],
  "Ext.grid.column.Template": [
    "widget.templatecolumn"
  ],
  "Ext.grid.feature.AbstractSummary": [
    "feature.abstractsummary"
  ],
  "Ext.grid.feature.Feature": [
    "feature.feature"
  ],
  "Ext.grid.feature.GroupStore": [],
  "Ext.grid.feature.Grouping": [
    "feature.grouping"
  ],
  "Ext.grid.feature.GroupingSummary": [
    "feature.groupingsummary"
  ],
  "Ext.grid.feature.RowBody": [
    "feature.rowbody"
  ],
  "Ext.grid.feature.RowWrap": [
    "feature.rowwrap"
  ],
  "Ext.grid.feature.Summary": [
    "feature.summary"
  ],
  "Ext.grid.header.Container": [
    "widget.headercontainer"
  ],
  "Ext.grid.header.DragZone": [],
  "Ext.grid.header.DropZone": [],
  "Ext.grid.locking.HeaderContainer": [],
  "Ext.grid.locking.Lockable": [],
  "Ext.grid.locking.View": [],
  "Ext.grid.plugin.BufferedRenderer": [
    "plugin.bufferedrenderer"
  ],
  "Ext.grid.plugin.BufferedRendererTableView": [],
  "Ext.grid.plugin.BufferedRendererTreeView": [],
  "Ext.grid.plugin.CellEditing": [
    "plugin.cellediting"
  ],
  "Ext.grid.plugin.DivRenderer": [
    "plugin.divrenderer"
  ],
  "Ext.grid.plugin.DragDrop": [
    "plugin.gridviewdragdrop"
  ],
  "Ext.grid.plugin.Editing": [
    "editing.editing"
  ],
  "Ext.grid.plugin.HeaderReorderer": [
    "plugin.gridheaderreorderer"
  ],
  "Ext.grid.plugin.HeaderResizer": [
    "plugin.gridheaderresizer"
  ],
  "Ext.grid.plugin.RowEditing": [
    "plugin.rowediting"
  ],
  "Ext.grid.plugin.RowExpander": [
    "plugin.rowexpander"
  ],
  "Ext.grid.property.Grid": [
    "widget.propertygrid"
  ],
  "Ext.grid.property.HeaderContainer": [],
  "Ext.grid.property.Property": [],
  "Ext.grid.property.Store": [],
  "Ext.layout.ClassList": [],
  "Ext.layout.Context": [],
  "Ext.layout.ContextItem": [],
  "Ext.layout.Layout": [],
  "Ext.layout.SizeModel": [],
  "Ext.layout.component.Auto": [
    "layout.autocomponent"
  ],
  "Ext.layout.component.Body": [
    "layout.body"
  ],
  "Ext.layout.component.BoundList": [
    "layout.boundlist"
  ],
  "Ext.layout.component.Button": [
    "layout.button"
  ],
  "Ext.layout.component.Component": [],
  "Ext.layout.component.Dock": [
    "layout.dock"
  ],
  "Ext.layout.component.Draw": [
    "layout.draw"
  ],
  "Ext.layout.component.FieldSet": [
    "layout.fieldset"
  ],
  "Ext.layout.component.ProgressBar": [
    "layout.progressbar"
  ],
  "Ext.layout.component.field.ComboBox": [
    "layout.combobox"
  ],
  "Ext.layout.component.field.Field": [
    "layout.field"
  ],
  "Ext.layout.component.field.FieldContainer": [
    "layout.fieldcontainer"
  ],
  "Ext.layout.component.field.HtmlEditor": [
    "layout.htmleditor"
  ],
  "Ext.layout.component.field.Slider": [
    "layout.sliderfield"
  ],
  "Ext.layout.component.field.Text": [
    "layout.textfield"
  ],
  "Ext.layout.component.field.TextArea": [
    "layout.textareafield"
  ],
  "Ext.layout.component.field.Trigger": [
    "layout.triggerfield"
  ],
  "Ext.layout.container.Absolute": [
    "layout.absolute"
  ],
  "Ext.layout.container.Accordion": [
    "layout.accordion"
  ],
  "Ext.layout.container.Anchor": [
    "layout.anchor"
  ],
  "Ext.layout.container.Auto": [
    "layout.auto",
    "layout.autocontainer"
  ],
  "Ext.layout.container.Border": [
    "layout.border"
  ],
  "Ext.layout.container.Box": [
    "layout.box"
  ],
  "Ext.layout.container.Card": [
    "layout.card"
  ],
  "Ext.layout.container.CheckboxGroup": [
    "layout.checkboxgroup"
  ],
  "Ext.layout.container.Column": [
    "layout.column"
  ],
  "Ext.layout.container.Container": [
    "layout.container"
  ],
  "Ext.layout.container.Editor": [
    "layout.editor"
  ],
  "Ext.layout.container.Fit": [
    "layout.fit"
  ],
  "Ext.layout.container.Form": [
    "layout.form"
  ],
  "Ext.layout.container.HBox": [
    "layout.hbox"
  ],
  "Ext.layout.container.Table": [
    "layout.table"
  ],
  "Ext.layout.container.VBox": [
    "layout.vbox"
  ],
  "Ext.layout.container.border.Region": [],
  "Ext.layout.container.boxOverflow.Menu": [],
  "Ext.layout.container.boxOverflow.None": [],
  "Ext.layout.container.boxOverflow.Scroller": [],
  "Ext.menu.CheckItem": [
    "widget.menucheckitem"
  ],
  "Ext.menu.ColorPicker": [
    "widget.colormenu"
  ],
  "Ext.menu.DatePicker": [
    "widget.datemenu"
  ],
  "Ext.menu.Item": [
    "widget.menuitem"
  ],
  "Ext.menu.KeyNav": [],
  "Ext.menu.Manager": [],
  "Ext.menu.Menu": [
    "widget.menu"
  ],
  "Ext.menu.Separator": [
    "widget.menuseparator"
  ],
  "Ext.panel.AbstractPanel": [],
  "Ext.panel.DD": [],
  "Ext.panel.Header": [
    "widget.header"
  ],
  "Ext.panel.Panel": [
    "widget.panel"
  ],
  "Ext.panel.Proxy": [],
  "Ext.panel.Table": [
    "widget.tablepanel"
  ],
  "Ext.panel.Tool": [
    "widget.tool"
  ],
  "Ext.picker.Color": [
    "widget.colorpicker"
  ],
  "Ext.picker.Date": [
    "widget.datepicker"
  ],
  "Ext.picker.Month": [
    "widget.monthpicker"
  ],
  "Ext.picker.Time": [
    "widget.timepicker"
  ],
  "Ext.resizer.BorderSplitter": [
    "widget.bordersplitter"
  ],
  "Ext.resizer.BorderSplitterTracker": [],
  "Ext.resizer.Handle": [],
  "Ext.resizer.ResizeTracker": [],
  "Ext.resizer.Resizer": [],
  "Ext.resizer.Splitter": [
    "widget.splitter"
  ],
  "Ext.resizer.SplitterTracker": [],
  "Ext.rtl.AbstractComponent": [],
  "Ext.rtl.EventObjectImpl": [],
  "Ext.rtl.button.Button": [],
  "Ext.rtl.dd.DD": [],
  "Ext.rtl.dom.Element_anim": [],
  "Ext.rtl.dom.Element_insertion": [],
  "Ext.rtl.dom.Element_position": [],
  "Ext.rtl.dom.Element_scroll": [],
  "Ext.rtl.dom.Element_static": [],
  "Ext.rtl.dom.Layer": [],
  "Ext.rtl.form.field.Checkbox": [],
  "Ext.rtl.form.field.File": [],
  "Ext.rtl.form.field.Spinner": [],
  "Ext.rtl.form.field.Trigger": [],
  "Ext.rtl.grid.CellEditor": [],
  "Ext.rtl.grid.RowEditor": [],
  "Ext.rtl.grid.column.Column": [],
  "Ext.rtl.grid.plugin.HeaderResizer": [],
  "Ext.rtl.grid.plugin.RowEditing": [],
  "Ext.rtl.layout.ContextItem": [],
  "Ext.rtl.layout.component.Dock": [],
  "Ext.rtl.layout.component.field.Text": [],
  "Ext.rtl.layout.component.field.Trigger": [],
  "Ext.rtl.layout.container.Absolute": [],
  "Ext.rtl.layout.container.Border": [],
  "Ext.rtl.layout.container.Box": [],
  "Ext.rtl.layout.container.CheckboxGroup": [],
  "Ext.rtl.layout.container.Column": [],
  "Ext.rtl.layout.container.HBox": [],
  "Ext.rtl.layout.container.VBox": [],
  "Ext.rtl.layout.container.boxOverflow.Menu": [],
  "Ext.rtl.layout.container.boxOverflow.Scroller": [],
  "Ext.rtl.panel.Header": [],
  "Ext.rtl.panel.Panel": [],
  "Ext.rtl.resizer.BorderSplitterTracker": [],
  "Ext.rtl.resizer.ResizeTracker": [],
  "Ext.rtl.resizer.SplitterTracker": [],
  "Ext.rtl.selection.CellModel": [],
  "Ext.rtl.selection.TreeModel": [],
  "Ext.rtl.slider.Multi": [],
  "Ext.rtl.tab.Bar": [],
  "Ext.rtl.tip.QuickTipManager": [],
  "Ext.rtl.tree.Column": [],
  "Ext.rtl.util.Floating": [],
  "Ext.rtl.util.Renderable": [],
  "Ext.rtl.view.Table": [],
  "Ext.selection.CellModel": [
    "selection.cellmodel"
  ],
  "Ext.selection.CheckboxModel": [
    "selection.checkboxmodel"
  ],
  "Ext.selection.DataViewModel": [],
  "Ext.selection.Model": [],
  "Ext.selection.RowModel": [
    "selection.rowmodel"
  ],
  "Ext.selection.TreeModel": [
    "selection.treemodel"
  ],
  "Ext.slider.Multi": [
    "widget.multislider"
  ],
  "Ext.slider.Single": [
    "widget.slider",
    "widget.sliderfield"
  ],
  "Ext.slider.Thumb": [],
  "Ext.slider.Tip": [
    "widget.slidertip"
  ],
  "Ext.state.CookieProvider": [],
  "Ext.state.LocalStorageProvider": [
    "state.localstorage"
  ],
  "Ext.state.Manager": [],
  "Ext.state.Provider": [],
  "Ext.state.Stateful": [],
  "Ext.tab.Bar": [
    "widget.tabbar"
  ],
  "Ext.tab.Panel": [
    "widget.tabpanel"
  ],
  "Ext.tab.Tab": [
    "widget.tab"
  ],
  "Ext.tip.QuickTip": [
    "widget.quicktip"
  ],
  "Ext.tip.QuickTipManager": [],
  "Ext.tip.Tip": [],
  "Ext.tip.ToolTip": [
    "widget.tooltip"
  ],
  "Ext.toolbar.Fill": [
    "widget.tbfill"
  ],
  "Ext.toolbar.Item": [
    "widget.tbitem"
  ],
  "Ext.toolbar.Paging": [
    "widget.pagingtoolbar"
  ],
  "Ext.toolbar.Separator": [
    "widget.tbseparator"
  ],
  "Ext.toolbar.Spacer": [
    "widget.tbspacer"
  ],
  "Ext.toolbar.TextItem": [
    "widget.tbtext"
  ],
  "Ext.toolbar.Toolbar": [
    "widget.toolbar"
  ],
  "Ext.tree.Column": [
    "widget.treecolumn"
  ],
  "Ext.tree.Panel": [
    "widget.treepanel"
  ],
  "Ext.tree.View": [
    "widget.treeview"
  ],
  "Ext.tree.ViewDragZone": [],
  "Ext.tree.ViewDropZone": [],
  "Ext.tree.plugin.TreeViewDragDrop": [
    "plugin.treeviewdragdrop"
  ],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Animate": [],
  "Ext.util.Bindable": [],
  "Ext.util.CSS": [],
  "Ext.util.ClickRepeater": [],
  "Ext.util.ComponentDragger": [],
  "Ext.util.Cookies": [],
  "Ext.util.ElementContainer": [],
  "Ext.util.Filter": [],
  "Ext.util.Floating": [],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.History": [],
  "Ext.util.Inflector": [],
  "Ext.util.KeyMap": [],
  "Ext.util.KeyNav": [],
  "Ext.util.LruCache": [],
  "Ext.util.Memento": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.Point": [],
  "Ext.util.ProtoElement": [],
  "Ext.util.Queue": [],
  "Ext.util.Region": [],
  "Ext.util.Renderable": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TextMetrics": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.ComboTriggerWindow": [
    "widget.combotriggerwindow"
  ],
  "Ext.ux.CropWindow": [
    "cropwindow"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.ImageCrop": [
    "imagecrop"
  ],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.PagingToolbarResizer": [
    "plugin.pagingtoolbarresizer"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.TreeFilter": [
    "plugin.treefilter"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Ext.ux.TreeTiggerWindow": [
    "widget.treetiggerwindow"
  ],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.form.MultiComboBox": [
    "widget.multicombobox"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.form.field.BoxSelect": [
    "widget.boxselect",
    "widget.comboboxselect"
  ],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Ext.ux.layout.component.field.BoxSelectField": [
    "layout.boxselectfield"
  ],
  "Ext.ux.oa.WorkFlow": [
    "widget.workflow"
  ],
  "Ext.ux.oa.WorkFlowPanel": [
    "widget.workflowpanel"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.uploadPanel.ImageUploadCropPanel": [
    "widget.imageuploadcroppanel"
  ],
  "Ext.ux.uploadPanel.UploadPanel": [
    "widget.uploadpanel"
  ],
  "Ext.view.AbstractView": [],
  "Ext.view.BoundList": [
    "widget.boundlist"
  ],
  "Ext.view.BoundListKeyNav": [],
  "Ext.view.DragZone": [],
  "Ext.view.DropZone": [],
  "Ext.view.NodeCache": [],
  "Ext.view.Table": [
    "widget.tableview"
  ],
  "Ext.view.TableLayout": [
    "layout.tableview"
  ],
  "Ext.view.View": [
    "widget.dataview"
  ],
  "Ext.window.MessageBox": [
    "widget.messagebox"
  ],
  "Ext.window.Window": [
    "widget.window"
  ],
  "Overrides.Number": [],
  "Overrides.data.Model": [],
  "Overrides.form.Basic": [],
  "Overrides.form.VTypes": [],
  "Overrides.form.field.Base": [],
  "Overrides.form.field.ComboBox": [],
  "Overrides.form.field.DisplayField": [],
  "Wenjoy.Application": [],
  "Wenjoy.controller.Base": [],
  "Wenjoy.controller.creditsdetail.CreditsDetail": [],
  "Wenjoy.controller.creditsdetail.SalesCommissionRule": [],
  "Wenjoy.controller.creditsdetail.TeamCommissionsRule": [],
  "Wenjoy.controller.customer.Customer": [],
  "Wenjoy.controller.dictdata.DictData": [],
  "Wenjoy.controller.dictdata.DictType": [],
  "Wenjoy.controller.doc.AppHelp": [],
  "Wenjoy.controller.inf.Message": [],
  "Wenjoy.controller.menu.Menu": [],
  "Wenjoy.controller.oa.CreditsExchange": [],
  "Wenjoy.controller.order.Order": [],
  "Wenjoy.controller.product.Product": [],
  "Wenjoy.controller.product.ProductLimit": [],
  "Wenjoy.controller.product.ProductType": [],
  "Wenjoy.controller.product.PublicProductApply": [],
  "Wenjoy.controller.product.Supplier": [],
  "Wenjoy.controller.role.Permission": [],
  "Wenjoy.controller.role.Role": [],
  "Wenjoy.controller.role.RoleType": [],
  "Wenjoy.controller.user.Agent": [],
  "Wenjoy.controller.user.Dept": [],
  "Wenjoy.controller.user.EvaluationType": [],
  "Wenjoy.controller.user.PositionLevel": [],
  "Wenjoy.controller.user.User": [],
  "Wenjoy.model.attachment.Attachment": [],
  "Wenjoy.model.creditsdetail.CreditsDetail": [],
  "Wenjoy.model.creditsdetail.SalesCommissionRule": [],
  "Wenjoy.model.creditsdetail.TeamCommissionsRule": [],
  "Wenjoy.model.customer.Contact": [],
  "Wenjoy.model.customer.Customer": [],
  "Wenjoy.model.dictdata.DictData": [],
  "Wenjoy.model.dictdata.DictType": [],
  "Wenjoy.model.doc.ApplicationHelper": [],
  "Wenjoy.model.inf.Message": [],
  "Wenjoy.model.inf.MessageReceive": [],
  "Wenjoy.model.menu.MenuTree": [],
  "Wenjoy.model.oa.CreditsExchange": [],
  "Wenjoy.model.order.Order": [],
  "Wenjoy.model.product.Product": [],
  "Wenjoy.model.product.ProductLimit": [],
  "Wenjoy.model.product.ProductType": [],
  "Wenjoy.model.product.ProductYieldRate": [],
  "Wenjoy.model.product.PublicProductApply": [],
  "Wenjoy.model.product.Supplier": [],
  "Wenjoy.model.role.Permission": [],
  "Wenjoy.model.role.Role": [],
  "Wenjoy.model.role.RoleBelongUser": [],
  "Wenjoy.model.role.RoleType": [],
  "Wenjoy.model.update.UpdateLog": [],
  "Wenjoy.model.user.Agent": [],
  "Wenjoy.model.user.DeptTree": [],
  "Wenjoy.model.user.EvaluationType": [],
  "Wenjoy.model.user.PositionLevel": [],
  "Wenjoy.model.user.User": [],
  "Wenjoy.store.attachment.Attachment": [],
  "Wenjoy.store.chart.DailyRaiseProgress": [],
  "Wenjoy.store.combo.Agent": [],
  "Wenjoy.store.combo.ApproveStateType": [],
  "Wenjoy.store.combo.CertificateType": [],
  "Wenjoy.store.combo.ComUser": [],
  "Wenjoy.store.combo.ComboDept": [],
  "Wenjoy.store.combo.ComboEvaluationtype": [],
  "Wenjoy.store.combo.ComboPositionLeveal": [],
  "Wenjoy.store.combo.ContractStateType": [],
  "Wenjoy.store.combo.CredetailSource": [],
  "Wenjoy.store.combo.CredetailState": [],
  "Wenjoy.store.combo.CredetailUserType": [],
  "Wenjoy.store.combo.CustomerDetail": [],
  "Wenjoy.store.combo.CustomerLevel": [],
  "Wenjoy.store.combo.CustomerSource": [],
  "Wenjoy.store.combo.CustomerType": [],
  "Wenjoy.store.combo.DictType": [],
  "Wenjoy.store.combo.MarriagedState": [],
  "Wenjoy.store.combo.NationType": [],
  "Wenjoy.store.combo.OrderDetail": [],
  "Wenjoy.store.combo.OrderSourceType": [],
  "Wenjoy.store.combo.OrderStateType": [],
  "Wenjoy.store.combo.Permission": [],
  "Wenjoy.store.combo.PoliticalStatusType": [],
  "Wenjoy.store.combo.ProCreditPromotionMeasures": [],
  "Wenjoy.store.combo.ProEarningAssign": [],
  "Wenjoy.store.combo.ProFundUse": [],
  "Wenjoy.store.combo.ProProjectLocation": [],
  "Wenjoy.store.combo.ProPublishState": [],
  "Wenjoy.store.combo.ProStateList": [],
  "Wenjoy.store.combo.ProTerm": [],
  "Wenjoy.store.combo.ProductDetail": [],
  "Wenjoy.store.combo.ProductType": [],
  "Wenjoy.store.combo.PublishProductState": [],
  "Wenjoy.store.combo.RoleType": [],
  "Wenjoy.store.combo.SectorType": [],
  "Wenjoy.store.combo.SexType": [],
  "Wenjoy.store.combo.StaffStateType": [],
  "Wenjoy.store.combo.StaffType": [],
  "Wenjoy.store.combo.StockholderBackgroundType": [],
  "Wenjoy.store.combo.Supplier": [],
  "Wenjoy.store.combo.SupplierType": [],
  "Wenjoy.store.creditsdetail.CreditsDetail": [],
  "Wenjoy.store.creditsdetail.SalesCommissionRule": [],
  "Wenjoy.store.creditsdetail.TeamCommissionsRule": [],
  "Wenjoy.store.customer.Contact": [],
  "Wenjoy.store.customer.Customer": [],
  "Wenjoy.store.dictdata.DictData": [],
  "Wenjoy.store.dictdata.DictType": [],
  "Wenjoy.store.inf.Message": [],
  "Wenjoy.store.inf.MessageReceive": [],
  "Wenjoy.store.menu.MenuPermission": [],
  "Wenjoy.store.menu.MenuTree": [],
  "Wenjoy.store.oa.CreditsExchange": [],
  "Wenjoy.store.oa.ProcessActivitiGraph": [],
  "Wenjoy.store.order.Order": [],
  "Wenjoy.store.product.Product": [],
  "Wenjoy.store.product.ProductLimit": [],
  "Wenjoy.store.product.ProductType": [],
  "Wenjoy.store.product.ProductYieldRate": [],
  "Wenjoy.store.product.PublicProductApply": [],
  "Wenjoy.store.product.Supplier": [],
  "Wenjoy.store.role.ByPermissionIdGetRole": [],
  "Wenjoy.store.role.ByRoleIdGetPermission": [],
  "Wenjoy.store.role.ByRoleTypeIdGetRole": [],
  "Wenjoy.store.role.Permission": [],
  "Wenjoy.store.role.Role": [],
  "Wenjoy.store.role.RoleBelongUser": [],
  "Wenjoy.store.role.RoleType": [],
  "Wenjoy.store.role.UserBelongPermission": [],
  "Wenjoy.store.role.UserBelongRole": [],
  "Wenjoy.store.update.UpdateLog": [],
  "Wenjoy.store.user.Agent": [],
  "Wenjoy.store.user.DeptTree": [],
  "Wenjoy.store.user.EvaluationType": [],
  "Wenjoy.store.user.PositionLevel": [],
  "Wenjoy.store.user.User": [],
  "Wenjoy.view.CenterPanel": [
    "widget.centerpanel"
  ],
  "Wenjoy.view.LeftMenu": [
    "widget.leftmenu"
  ],
  "Wenjoy.view.TopPanel": [
    "widget.toppanel"
  ],
  "Wenjoy.view.Viewport": [],
  "Wenjoy.view.chart.DailyRaiseProgressLineChart": [
    "widget.dailyraiseprogresslinechart"
  ],
  "Wenjoy.view.chart.UploadExcel": [],
  "Wenjoy.view.common.AttachmentUpload": [
    "widget.attachmentupload"
  ],
  "Wenjoy.view.common.ExcelImport": [
    "widget.excelimport"
  ],
  "Wenjoy.view.common.ExtKindEditor": [
    "widget.extkindeditor"
  ],
  "Wenjoy.view.common.ImageUpload": [
    "widget.imageupload"
  ],
  "Wenjoy.view.common.PermissionAdjust": [
    "widget.permissionadjust"
  ],
  "Wenjoy.view.common.PwdModify": [
    "widget.pwdmodify"
  ],
  "Wenjoy.view.common.RoleAdjust": [
    "widget.roleadjust"
  ],
  "Wenjoy.view.common.UserAdjust": [
    "widget.useradjust"
  ],
  "Wenjoy.view.common.WorkFlowGraphWindow": [
    "widget.workflowgraphwindow"
  ],
  "Wenjoy.view.creditsdetail.CreditsDetailDetail": [
    "widget.creditsdetaildetail"
  ],
  "Wenjoy.view.creditsdetail.CreditsDetailEdit": [
    "widget.creditsdetailedit"
  ],
  "Wenjoy.view.creditsdetail.CreditsDetailList": [
    "widget.creditsdetaillist"
  ],
  "Wenjoy.view.creditsdetail.SalesCommissionRuleDetail": [
    "widget.salescommissionruledetail"
  ],
  "Wenjoy.view.creditsdetail.SalesCommissionRuleEdit": [
    "widget.salescommissionruleedit"
  ],
  "Wenjoy.view.creditsdetail.SalesCommissionRuleList": [
    "widget.salessommissionrulelist"
  ],
  "Wenjoy.view.creditsdetail.TeamCommissionsRuleDetail": [
    "widget.teamcommissionsruledetail"
  ],
  "Wenjoy.view.creditsdetail.TeamCommissionsRuleEdit": [
    "widget.teamcommissionsruleedit"
  ],
  "Wenjoy.view.creditsdetail.TeamCommissionsRuleList": [
    "widget.teamcommissionsrulelist"
  ],
  "Wenjoy.view.customer.ContactDetail": [
    "widget.contactdetail"
  ],
  "Wenjoy.view.customer.ContactEdit": [
    "widget.contactedit"
  ],
  "Wenjoy.view.customer.CustomerDetail": [
    "widget.customerdetail"
  ],
  "Wenjoy.view.customer.CustomerEdit": [
    "widget.customeredit"
  ],
  "Wenjoy.view.customer.CustomerList": [
    "widget.customerlist"
  ],
  "Wenjoy.view.dictdata.DictDataEdit": [
    "widget.dictdataedit"
  ],
  "Wenjoy.view.dictdata.DictDataList": [
    "widget.dictdatalist"
  ],
  "Wenjoy.view.dictdata.DictTypeEdit": [
    "widget.dicttypeedit"
  ],
  "Wenjoy.view.dictdata.DictTypeList": [
    "widget.dicttypelist"
  ],
  "Wenjoy.view.doc.AppHelpIndex": [
    "widget.appHelpIndex"
  ],
  "Wenjoy.view.doc.AppHelperDetail": [
    "widget.appHelperDetail"
  ],
  "Wenjoy.view.doc.AppHelperMenuEdit": [
    "widget.appHelperMenuEdit"
  ],
  "Wenjoy.view.inf.MessageEdit": [
    "widget.messageeditview"
  ],
  "Wenjoy.view.inf.MessageList": [
    "widget.messagelistview"
  ],
  "Wenjoy.view.menu.Edit": [
    "widget.menuedit"
  ],
  "Wenjoy.view.menu.MenuTree": [
    "widget.menutree"
  ],
  "Wenjoy.view.oa.CreditsExchangeDetail": [
    "widget.creditsexchangedetail"
  ],
  "Wenjoy.view.oa.CreditsExchangeEdit": [
    "widget.creditsexchangeedit"
  ],
  "Wenjoy.view.oa.CreditsExchangeList": [
    "widget.creditsexchangelist"
  ],
  "Wenjoy.view.order.AppendOrderList": [
    "widget.orderappendorderlist"
  ],
  "Wenjoy.view.order.OrderDeal": [],
  "Wenjoy.view.order.OrderEdit": [
    "widget.orderedit"
  ],
  "Wenjoy.view.order.OrderList": [
    "widget.orderlist"
  ],
  "Wenjoy.view.order.OrderMoneyAccount": [
    "widget.ordermoneyaccount"
  ],
  "Wenjoy.view.order.OrderRemark": [
    "widget.orderremark"
  ],
  "Wenjoy.view.portlet.ChartPortlet": [
    "widget.chartportlet"
  ],
  "Wenjoy.view.portlet.GridPortlet": [
    "widget.gridportlet"
  ],
  "Wenjoy.view.portlet.PortalColumn": [
    "widget.portalcolumn"
  ],
  "Wenjoy.view.portlet.PortalDropZone": [],
  "Wenjoy.view.portlet.PortalPanel": [
    "widget.portalpanel"
  ],
  "Wenjoy.view.portlet.Portlet": [
    "widget.portlet"
  ],
  "Wenjoy.view.product.FeeRateList": [
    "widget.feeratelistview"
  ],
  "Wenjoy.view.product.ProductDetail": [
    "widget.productdetail"
  ],
  "Wenjoy.view.product.ProductEdit": [
    "widget.producteditview"
  ],
  "Wenjoy.view.product.ProductLimitEdit": [
    "widget.productlimiteditview"
  ],
  "Wenjoy.view.product.ProductLimitList": [
    "widget.productlimitlistview"
  ],
  "Wenjoy.view.product.ProductList": [
    "widget.productlistview"
  ],
  "Wenjoy.view.product.ProductRateOrSalesCommission": [
    "widget.productrateOrsalescommission"
  ],
  "Wenjoy.view.product.ProductTypeDetail": [
    "widget.producttypedetail"
  ],
  "Wenjoy.view.product.ProductTypeEdit": [
    "widget.producttypeeditview"
  ],
  "Wenjoy.view.product.ProductTypeList": [
    "widget.producttypelistview"
  ],
  "Wenjoy.view.product.ProductYieldRateDetail": [
    "widget.productyieldratedetail"
  ],
  "Wenjoy.view.product.ProductYieldRateEdit": [
    "widget.productyieldrateedit"
  ],
  "Wenjoy.view.product.PublicProductApplyEdit": [
    "widget.publicproductapplyedit"
  ],
  "Wenjoy.view.product.PublicProductApplyList": [
    "widget.publicproductapplylist"
  ],
  "Wenjoy.view.product.SalesCommissionList": [
    "widget.salescommissionlistview"
  ],
  "Wenjoy.view.product.SupplierDetail": [
    "widget.supplierdetail"
  ],
  "Wenjoy.view.product.SupplierEdit": [
    "widget.suppliereditview"
  ],
  "Wenjoy.view.product.SupplierList": [
    "widget.supplierlistview"
  ],
  "Wenjoy.view.role.PermissionDetail": [
    "widget.rolepermissiondetail"
  ],
  "Wenjoy.view.role.PermissionEdit": [
    "widget.rolepermissionedit"
  ],
  "Wenjoy.view.role.PermissionList": [
    "widget.rolepermissionlist"
  ],
  "Wenjoy.view.role.PermissionSourceEdit": [
    "widget.rolepermissionsourceedit"
  ],
  "Wenjoy.view.role.PermissionTable": [
    "widget.permissionTable"
  ],
  "Wenjoy.view.role.RoleDetail": [
    "widget.roleroledetail"
  ],
  "Wenjoy.view.role.RoleEdit": [
    "widget.roleroleedit"
  ],
  "Wenjoy.view.role.RoleList": [
    "widget.rolerolelist"
  ],
  "Wenjoy.view.role.RoleTypeDetail": [
    "widget.roletypedetail"
  ],
  "Wenjoy.view.role.RoleTypeEdit": [
    "widget.roleroletypeedit"
  ],
  "Wenjoy.view.role.RoleTypeList": [
    "widget.roleroletypelist"
  ],
  "Wenjoy.view.role.UserTable": [
    "widget.userTable"
  ],
  "Wenjoy.view.user.AgentEdit": [
    "widget.agentedit"
  ],
  "Wenjoy.view.user.AgentList": [
    "widget.agentlist"
  ],
  "Wenjoy.view.user.DeptEdit": [
    "widget.deptedit"
  ],
  "Wenjoy.view.user.DeptTree": [
    "widget.depttree"
  ],
  "Wenjoy.view.user.EvaluationTypeDetail": [
    "widget.evaluationtypedetail"
  ],
  "Wenjoy.view.user.EvaluationTypeEdit": [
    "widget.evaluationtypeedit"
  ],
  "Wenjoy.view.user.EvaluationTypeList": [
    "widget.evaluationtypelist"
  ],
  "Wenjoy.view.user.PositionLevelDetail": [
    "widget.positionleveldetail"
  ],
  "Wenjoy.view.user.PositionLevelEdit": [
    "widget.positionleveledit"
  ],
  "Wenjoy.view.user.PositionLevelList": [
    "widget.positionlevellist"
  ],
  "Wenjoy.view.user.PositionLevelSourceEdit": [
    "widget.positionlevelsourceedit"
  ],
  "Wenjoy.view.user.ReferUserList": [
    "widget.userreferuserlist"
  ],
  "Wenjoy.view.user.UserDetail": [
    "widget.userdetail"
  ],
  "Wenjoy.view.user.UserEdit": [
    "widget.useruseredit"
  ],
  "Wenjoy.view.user.UserList": [
    "widget.useruserlist"
  ],
  "account": []
});
Ext.setVersion("ext-theme-base", "4.2.1");
Ext.setVersion("ext-theme-classic", "4.2.1");
Ext.setVersion("ext-theme-neutral", "4.2.1");
/**
 * Sencha Blink - Development
 * @author Jacky Nguyen <jacky@sencha.com>
 */
(function() {
    var head = document.head;

    function write(content) {
        document.write(content);
    }

    function addMeta(name, content) {
        var meta = document.createElement('meta');

        meta.setAttribute('name', name);
        meta.setAttribute('content', content);
        head.appendChild(meta);
    }

    var xhr = new XMLHttpRequest();
    xhr.open('GET', 'bootstrap.json', false);
    xhr.send(null);

    var options = eval("(" + xhr.responseText + ")"),
        scripts = options.js || [],
        styleSheets = options.css || [],
        i, ln, path, platform, theme, exclude;

    if(options.platform && options.platforms && options.platforms[options.platform] && options.platforms[options.platform].js) {
        scripts = options.platforms[options.platform].js.concat(scripts);
    }

    if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
            document.createTextNode(
                "@media screen and (orientation: portrait) {" +
                    "@-ms-viewport {width: 320px !important;}" +
                "}" +
                "@media screen and (orientation: landscape) {" +
                    "@-ms-viewport {width: 560px !important;}" +
                "}"
            )
        );
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    addMeta('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no');
    addMeta('apple-mobile-web-app-capable', 'yes');
    addMeta('apple-touch-fullscreen', 'yes');

    if (!window.Ext) {
        window.Ext = {};
    }
    Ext.microloaded = true;

    var filterPlatform = window.Ext.filterPlatform = function(platform) {
        var profileMatch = false,
            ua = navigator.userAgent,
            j, jln;

        platform = [].concat(platform);

        function isPhone(ua) {
            var isMobile = /Mobile(\/|\s)/.test(ua);

            // Either:
            // - iOS but not iPad
            // - Android 2
            // - Android with "Mobile" in the UA

            return /(iPhone|iPod)/.test(ua) ||
                      (!/(Silk)/.test(ua) && (/(Android)/.test(ua) && (/(Android 2)/.test(ua) || isMobile))) ||
                      (/(BlackBerry|BB)/.test(ua) && isMobile) ||
                      /(Windows Phone)/.test(ua);
        }

        function isTablet(ua) {
            return !isPhone(ua) && (/iPad/.test(ua) || /Android|Silk/.test(ua) || /(RIM Tablet OS)/.test(ua) ||
                (/MSIE 10/.test(ua) && /; Touch/.test(ua)));
        }

        // Check if the ?platform parameter is set in the URL
        var paramsString = window.location.search.substr(1),
            paramsArray = paramsString.split("&"),
            params = {},
            testPlatform, i;

        for (i = 0; i < paramsArray.length; i++) {
            var tmpArray = paramsArray[i].split("=");
            params[tmpArray[0]] = tmpArray[1];
        }

        testPlatform = params.platform;
        if (testPlatform) {
            return platform.indexOf(testPlatform) != -1;
        }

        for (j = 0, jln = platform.length; j < jln; j++) {
            switch (platform[j]) {
                case 'phone':
                    profileMatch = isPhone(ua);
                    break;
                case 'tablet':
                    profileMatch = isTablet(ua);
                    break;
                case 'desktop':
                    profileMatch = !isPhone(ua) && !isTablet(ua);
                    break;
                case 'ios':
                    profileMatch = /(iPad|iPhone|iPod)/.test(ua);
                    break;
                case 'android':
                    profileMatch = /(Android|Silk)/.test(ua);
                    break;
                case 'blackberry':
                    profileMatch = /(BlackBerry|BB)/.test(ua);
                    break;
                case 'safari':
                    profileMatch = /Safari/.test(ua) && !(/(BlackBerry|BB)/.test(ua));
                    break;
                case 'chrome':
                    profileMatch = /Chrome/.test(ua);
                    break;
                case 'ie10':
                    profileMatch = /MSIE 10/.test(ua);
                    break;
                case 'windows':
                    profileMatch = /MSIE 10/.test(ua) || /Trident/.test(ua);
                    break;
                case 'tizen':
                    profileMatch = /Tizen/.test(ua);
                    break;
                case 'firefox':
                    profileMatch = /Firefox/.test(ua);
            }
            if (profileMatch) {
                return true;
            }
        }
        return false;
    };


    for (i = 0,ln = styleSheets.length; i < ln; i++) {
        path = styleSheets[i];

        if (typeof path != 'string') {
            platform = path.platform;
            exclude = path.exclude;
            theme = path.theme;
            path = path.path;
        }

        if (platform) {
            if (!filterPlatform(platform) || filterPlatform(exclude)) {
                continue;
            }
            Ext.theme = {
                name: theme || 'Default'
            };
        }

        write('<link rel="stylesheet" href="'+path+'">');
    }

    for (i = 0,ln = scripts.length; i < ln; i++) {
        path = scripts[i];

        if (typeof path != 'string') {
            platform = path.platform;
            exclude = path.exclude;
            path = path.path;
        }

        if (platform) {
            if (!filterPlatform(platform) || filterPlatform(exclude)) {
                continue;
            }
        }

        write('<script src="'+path+'"></'+'script>');
    }

})();